export const genshinCharacters = [
    {
        name: '甘雨',
        url: 'https://docker.chunkj.dpdns.org',
        element: '冰',
        rarity: 5,
        color: '#4A90E2',
        description: 'Docker加速服务',
        vision: '冰',
        weapon: '弓',
        region: '璃月',
        imageUrl: 'https://i.pixiv.re/img-original/img/2023/10/24/00/01/01/112799095_p0.jpg'
    },
    {
        name: '胡桃',
        url: 'https://gh-proxy.chunkj.dpdns.org',
        element: '火',
        rarity: 5,
        color: '#E74C3C',
        description: 'GitHub加速服务',
        vision: '火',
        weapon: '长柄武器',
        region: '璃月',
        imageUrl: 'https://i.imgur.com/placeholder2.jpg'
    },
    {
        name: '雷电将军',
        url: 'https://rss-gpt.chunkj.dpdns.org',
        element: '雷',
        rarity: 5,
        color: '#9B59B6',
        description: 'RSS智能订阅',
        vision: '雷',
        weapon: '剑',
        region: '稻妻',
        imageUrl: 'https://i.imgur.com/placeholder3.jpg'
    },
    {
        name: '钟离',
        url: 'https://sub-web-plus.chunkj.dpdns.org',
        element: '岩',
        rarity: 5,
        color: '#F39C12',
        description: '订阅格式转换',
        vision: '岩',
        weapon: '长柄武器',
        region: '璃月',
        imageUrl: 'https://i.imgur.com/placeholder4.jpg'
    },
    {
        name: '魈',
        url: 'https://supersonic.chunkj.dpdns.org',
        element: '风',
        rarity: 5,
        color: '#2ECC71',
        description: '音乐流媒体',
        vision: '风',
        weapon: '长柄武器',
        region: '璃月',
        imageUrl: 'https://i.imgur.com/placeholder5.jpg'
    },
    {
        name: '八重神子',
        url: 'https://docker.chunkj.us.to',
        element: '雷',
        rarity: 5,
        color: '#E91E63',
        description: '备用加速服务',
        vision: '雷',
        weapon: '法器',
        region: '稻妻',
        imageUrl: 'https://i.imgur.com/placeholder6.jpg'
    },
    {
        name: '温迪',
        url: 'https://gh-fast.chunkj.dpdns.org',
        element: '风',
        rarity: 5,
        color: '#00BCD4',
        description: '备用代码加速',
        vision: '风',
        weapon: '弓',
        region: '蒙德',
        imageUrl: 'https://i.imgur.com/placeholder7.jpg'
    },
    {
        name: '刻晴',
        url: 'https://snake.chunkj.dpdns.org',
        element: '雷',
        rarity: 5,
        color: '#9C27B0',
        description: '经典小游戏',
        vision: '雷',
        weapon: '剑',
        region: '璃月',
        imageUrl: 'https://i.imgur.com/placeholder8.jpg'
    },
    {
        name: '迪卢克',
        url: 'https://yang.chunkj.dpdns.org',
        element: '火',
        rarity: 5,
        color: '#FF5722',
        description: '热门消除游戏',
        vision: '火',
        weapon: '双手剑',
        region: '蒙德',
        imageUrl: 'https://i.imgur.com/placeholder9.jpg'
    },
    {
        name: '芭芭拉',
        url: 'https://tophub.you.hidns.vip',
        element: '水',
        rarity: 4,
        color: '#2196F3',
        description: '热点新闻聚合',
        vision: '水',
        weapon: '法器',
        region: '蒙德',
        imageUrl: 'https://i.imgur.com/placeholder10.jpg'
    },
    {
        name: '菲谢尔',
        url: 'https://tophub.chunkj.us.to',
        element: '雷',
        rarity: 4,
        color: '#673AB7',
        description: '备用热点服务',
        vision: '雷',
        weapon: '弓',
        region: '蒙德',
        imageUrl: 'https://i.imgur.com/placeholder11.jpg'
    },
    {
        name: '香菱',
        url: 'https://tv.chunkj.dpdns.org',
        element: '火',
        rarity: 4,
        color: '#FF9800',
        description: '在线电视直播',
        vision: '火',
        weapon: '长柄武器',
        region: '璃月',
        imageUrl: 'https://i.imgur.com/placeholder12.jpg'
    },
    {
        name: '北斗',
        url: 'https://awesome-ollama.chunkj.dpdns.org',
        element: '雷',
        rarity: 4,
        color: '#3F51B5',
        description: 'Ollama模型服务',
        vision: '雷',
        weapon: '双手剑',
        region: '璃月',
        imageUrl: 'https://i.imgur.com/placeholder13.jpg'
    },
    {
        name: '派蒙',
        url: 'https://rand.mossia.top/',
        element: '风',
        rarity: 5, 
        color: '#FFD700',
        description: '随机图片生成器',
        vision: '风',
        weapon: '法器',
        region: '天空岛',
        imageUrl: 'https://i.imgur.com/placeholder14.jpg'
    }
]; 